import { createFileRoute } from "@tanstack/react-router";
import { useEffect } from "react";
import "@/styles/portfolio.css";

export const Route = createFileRoute("/portfolio/luxury")({
  component: LuxuryCaseStudy,
});

function LuxuryCaseStudy() {
  useEffect(() => {
    const link1 = document.createElement("link");
    link1.rel = "preconnect";
    link1.href = "https://fonts.googleapis.com";
    document.head.appendChild(link1);

    const link2 = document.createElement("link");
    link2.rel = "preconnect";
    link2.href = "https://fonts.gstatic.com";
    link2.crossOrigin = "anonymous";
    document.head.appendChild(link2);

    const link3 = document.createElement("link");
    link3.href =
      "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,400&display=swap";
    link3.rel = "stylesheet";
    document.head.appendChild(link3);

    return () => {
      document.head.removeChild(link1);
      document.head.removeChild(link2);
      document.head.removeChild(link3);
    };
  }, []);

  return (
    <div className="portfolio-page">
      <div className="page">
        <div className="page-header">
          <span className="page-header__logo">Your Company</span>
          <span className="page-header__title">Case Study</span>
        </div>

        <div className="case-title-section">
          <div className="case-number">Case Study 05</div>
          <div className="case-client">Global Luxury Brand</div>
          <div className="case-project-title">
            Transforming Security Operations Through Intelligent Case Automation
          </div>
        </div>

        <div className="case-meta">
          <div className="case-meta__item">
            <span className="case-meta__label">Industry</span>
            <span className="case-meta__value">Retail & Luxury Goods</span>
          </div>
          <div className="case-meta__item">
            <span className="case-meta__label">Engagement</span>
            <span className="case-meta__value">Direct Engagement</span>
          </div>
          <div className="case-meta__item">
            <span className="case-meta__label">Focus Areas</span>
            <div className="tags">
              <span className="tag">Security Ops</span>
              <span className="tag">Automation</span>
              <span className="tag">AI/ML</span>
            </div>
          </div>
        </div>

        <h4>The Challenge</h4>
        <p>
          For a prestigious global luxury brand, protecting the business from security threats
          requires constant vigilance. The security operations team relied on email-based alerts
          generated by existing filtering rules—a system that successfully flagged unusual
          activities but produced a significant volume of false positives.
        </p>
        <p>
          Security officers faced a daily deluge of alerts arriving in their inboxes. Each case
          demanded manual investigation: reading through email threads, cross-referencing historical
          incidents, and determining whether the alert warranted action. Critical alerts risked
          being buried in overflowing inboxes, and institutional knowledge remained trapped in
          scattered email chains.
        </p>

        <h4>The Approach</h4>
        <p>
          We designed and implemented an intelligent security case management platform that
          transforms raw alerts into actionable intelligence.
        </p>

        <p>
          <strong>Automated Alert Ingestion & Enrichment</strong>
          <br />
          Using Microsoft Power Automate, we built integration pipelines that capture alerts from
          the existing email filtering system and ingest them into Microsoft Dataverse. Each alert
          is automatically enriched with contextual data, creating structured case records.
        </p>

        <p>
          <strong>Machine Learning Classification</strong>
          <br />
          Rather than treating every alert equally, we implemented ML models that analyze each case
          against historical patterns. The system learns from officer feedback, continuously
          improving its ability to distinguish genuine threats from false positives.
        </p>

        <p>
          <strong>Real-Time Teams Integration</strong>
          <br />
          Security officers now receive intelligent notifications directly in Microsoft Teams. Each
          alert card includes case summary, risk assessment, and one-click action buttons—enabling
          officers to flag, escalate, or dismiss cases without leaving their workflow.
        </p>

        <p>
          <strong>Conversational Intelligence with Copilot Studio</strong>
          <br />
          We deployed a custom Copilot Studio agent that enables security teams to query historical
          cases through natural conversation. Officers can ask questions like "Show me similar cases
          from this user in the past 6 months"—surfacing insights that previously required hours of
          email archaeology.
        </p>

        <p>
          <strong>Unified Analytics & Continuous Improvement</strong>
          <br />
          With all case data consolidated in Dataverse, we delivered Power BI dashboards providing
          real-time visibility into alert volumes, response times, and team performance. The unified
          data layer enables continuous refinement of ML models.
        </p>

        <h4>The Impact</h4>

        <div className="impact-grid">
          <div className="impact-card">
            <div className="impact-card__metric">Hours → Minutes</div>
            <div className="impact-card__label">Response time with Teams-based triage</div>
          </div>
          <div className="impact-card">
            <div className="impact-card__metric">Unified Data</div>
            <div className="impact-card__label">All historical cases searchable via AI</div>
          </div>
          <div className="impact-card">
            <div className="impact-card__metric">Continuous Learning</div>
            <div className="impact-card__label">ML improvement based on officer feedback</div>
          </div>
          <div className="impact-card">
            <div className="impact-card__metric">Full Visibility</div>
            <div className="impact-card__label">Real-time dashboards for leadership</div>
          </div>
        </div>

        <blockquote>
          <p>
            The platform transformed security operations from reactive email monitoring to
            proactive, intelligence-driven threat management.
          </p>
        </blockquote>

        <div className="page-footer">
          <span>Confidential Client</span>
          <span>© 2026 Your Company</span>
        </div>
      </div>
    </div>
  );
}
