/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PortfolioIndexRouteImport } from "./routes/portfolio/index"
import { Route as PortfolioTuitionRouteImport } from "./routes/portfolio/tuition"
import { Route as PortfolioThemeParkRouteImport } from "./routes/portfolio/theme-park"
import { Route as PortfolioSourcingRouteImport } from "./routes/portfolio/sourcing"
import { Route as PortfolioRemittanceRouteImport } from "./routes/portfolio/remittance"
import { Route as PortfolioMobilityRouteImport } from "./routes/portfolio/mobility"
import { Route as PortfolioLuxuryRouteImport } from "./routes/portfolio/luxury"
import { Route as PortfolioFinancialRouteImport } from "./routes/portfolio/financial"

const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: "/portfolio/",
  path: "/portfolio/",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTuitionRoute = PortfolioTuitionRouteImport.update({
  id: "/portfolio/tuition",
  path: "/portfolio/tuition",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioThemeParkRoute = PortfolioThemeParkRouteImport.update({
  id: "/portfolio/theme-park",
  path: "/portfolio/theme-park",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSourcingRoute = PortfolioSourcingRouteImport.update({
  id: "/portfolio/sourcing",
  path: "/portfolio/sourcing",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRemittanceRoute = PortfolioRemittanceRouteImport.update({
  id: "/portfolio/remittance",
  path: "/portfolio/remittance",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioMobilityRoute = PortfolioMobilityRouteImport.update({
  id: "/portfolio/mobility",
  path: "/portfolio/mobility",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioLuxuryRoute = PortfolioLuxuryRouteImport.update({
  id: "/portfolio/luxury",
  path: "/portfolio/luxury",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioFinancialRoute = PortfolioFinancialRouteImport.update({
  id: "/portfolio/financial",
  path: "/portfolio/financial",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/portfolio/financial": typeof PortfolioFinancialRoute
  "/portfolio/luxury": typeof PortfolioLuxuryRoute
  "/portfolio/mobility": typeof PortfolioMobilityRoute
  "/portfolio/remittance": typeof PortfolioRemittanceRoute
  "/portfolio/sourcing": typeof PortfolioSourcingRoute
  "/portfolio/theme-park": typeof PortfolioThemeParkRoute
  "/portfolio/tuition": typeof PortfolioTuitionRoute
  "/portfolio": typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/portfolio/financial": typeof PortfolioFinancialRoute
  "/portfolio/luxury": typeof PortfolioLuxuryRoute
  "/portfolio/mobility": typeof PortfolioMobilityRoute
  "/portfolio/remittance": typeof PortfolioRemittanceRoute
  "/portfolio/sourcing": typeof PortfolioSourcingRoute
  "/portfolio/theme-park": typeof PortfolioThemeParkRoute
  "/portfolio/tuition": typeof PortfolioTuitionRoute
  "/portfolio": typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/portfolio/financial": typeof PortfolioFinancialRoute
  "/portfolio/luxury": typeof PortfolioLuxuryRoute
  "/portfolio/mobility": typeof PortfolioMobilityRoute
  "/portfolio/remittance": typeof PortfolioRemittanceRoute
  "/portfolio/sourcing": typeof PortfolioSourcingRoute
  "/portfolio/theme-park": typeof PortfolioThemeParkRoute
  "/portfolio/tuition": typeof PortfolioTuitionRoute
  "/portfolio/": typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/portfolio/financial"
    | "/portfolio/luxury"
    | "/portfolio/mobility"
    | "/portfolio/remittance"
    | "/portfolio/sourcing"
    | "/portfolio/theme-park"
    | "/portfolio/tuition"
    | "/portfolio"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/portfolio/financial"
    | "/portfolio/luxury"
    | "/portfolio/mobility"
    | "/portfolio/remittance"
    | "/portfolio/sourcing"
    | "/portfolio/theme-park"
    | "/portfolio/tuition"
    | "/portfolio"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/portfolio/financial"
    | "/portfolio/luxury"
    | "/portfolio/mobility"
    | "/portfolio/remittance"
    | "/portfolio/sourcing"
    | "/portfolio/theme-park"
    | "/portfolio/tuition"
    | "/portfolio/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PortfolioFinancialRoute: typeof PortfolioFinancialRoute
  PortfolioLuxuryRoute: typeof PortfolioLuxuryRoute
  PortfolioMobilityRoute: typeof PortfolioMobilityRoute
  PortfolioRemittanceRoute: typeof PortfolioRemittanceRoute
  PortfolioSourcingRoute: typeof PortfolioSourcingRoute
  PortfolioThemeParkRoute: typeof PortfolioThemeParkRoute
  PortfolioTuitionRoute: typeof PortfolioTuitionRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/": {
      id: "/portfolio/"
      path: "/portfolio"
      fullPath: "/portfolio"
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/tuition": {
      id: "/portfolio/tuition"
      path: "/portfolio/tuition"
      fullPath: "/portfolio/tuition"
      preLoaderRoute: typeof PortfolioTuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/theme-park": {
      id: "/portfolio/theme-park"
      path: "/portfolio/theme-park"
      fullPath: "/portfolio/theme-park"
      preLoaderRoute: typeof PortfolioThemeParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/sourcing": {
      id: "/portfolio/sourcing"
      path: "/portfolio/sourcing"
      fullPath: "/portfolio/sourcing"
      preLoaderRoute: typeof PortfolioSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/remittance": {
      id: "/portfolio/remittance"
      path: "/portfolio/remittance"
      fullPath: "/portfolio/remittance"
      preLoaderRoute: typeof PortfolioRemittanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/mobility": {
      id: "/portfolio/mobility"
      path: "/portfolio/mobility"
      fullPath: "/portfolio/mobility"
      preLoaderRoute: typeof PortfolioMobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/luxury": {
      id: "/portfolio/luxury"
      path: "/portfolio/luxury"
      fullPath: "/portfolio/luxury"
      preLoaderRoute: typeof PortfolioLuxuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio/financial": {
      id: "/portfolio/financial"
      path: "/portfolio/financial"
      fullPath: "/portfolio/financial"
      preLoaderRoute: typeof PortfolioFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PortfolioFinancialRoute: PortfolioFinancialRoute,
  PortfolioLuxuryRoute: PortfolioLuxuryRoute,
  PortfolioMobilityRoute: PortfolioMobilityRoute,
  PortfolioRemittanceRoute: PortfolioRemittanceRoute,
  PortfolioSourcingRoute: PortfolioSourcingRoute,
  PortfolioThemeParkRoute: PortfolioThemeParkRoute,
  PortfolioTuitionRoute: PortfolioTuitionRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
